import {
  StepBackwardOutlined,
  StepForwardOutlined,
  FastBackwardOutlined,
  FastForwardOutlined,
  ShrinkOutlined,
  ArrowsAltOutlined,
  DownOutlined,
  UpOutlined,
  LeftOutlined,
  RightOutlined,
  CaretUpOutlined,
  CaretDownOutlined,
  CaretLeftOutlined,
  CaretRightOutlined,
  UpCircleOutlined,
  DownCircleOutlined,
  LeftCircleOutlined,
  RightCircleOutlined,
  DoubleRightOutlined,
  DoubleLeftOutlined,
  VerticalLeftOutlined,
  VerticalRightOutlined,
  VerticalAlignTopOutlined,
  VerticalAlignMiddleOutlined,
  VerticalAlignBottomOutlined,
  ForwardOutlined,
  BackwardOutlined,
  RollbackOutlined,
  EnterOutlined,
  RetweetOutlined,
  SwapOutlined,
  SwapLeftOutlined,
  SwapRightOutlined,
  ArrowUpOutlined,
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowRightOutlined,
  PlayCircleOutlined,
  UpSquareOutlined,
  DownSquareOutlined,
  LeftSquareOutlined,
  RightSquareOutlined,
  LoginOutlined,
  LogoutOutlined,
  MenuFoldOutlined,
  MenuUnfoldOutlined,
  BorderBottomOutlined,
  BorderHorizontalOutlined,
  BorderInnerOutlined,
  BorderOuterOutlined,
  BorderLeftOutlined,
  BorderRightOutlined,
  BorderTopOutlined,
  BorderVerticleOutlined,
  PicCenterOutlined,
  PicLeftOutlined,
  PicRightOutlined,
  RadiusBottomleftOutlined,
  RadiusBottomrightOutlined,
  RadiusUpleftOutlined,
  RadiusUprightOutlined,
  FullscreenOutlined,
  FullscreenExitOutlined,
  QuestionOutlined,
  QuestionCircleOutlined,
  PlusOutlined,
  PlusCircleOutlined,
  PauseOutlined,
  PauseCircleOutlined,
  MinusOutlined,
  MinusCircleOutlined,
  PlusSquareOutlined,
  MinusSquareOutlined,
  InfoOutlined,
  InfoCircleOutlined,
  ExclamationOutlined,
  ExclamationCircleOutlined,
  CloseOutlined,
  CloseCircleOutlined,
  CloseSquareOutlined,
  CheckOutlined,
  CheckCircleOutlined,
  CheckSquareOutlined,
  ClockCircleOutlined,
  WarningOutlined,
  IssuesCloseOutlined,
  StopOutlined,
  EditOutlined,
  FormOutlined,
  CopyOutlined,
  ScissorOutlined,
  DeleteOutlined,
  SnippetsOutlined,
  DiffOutlined,
  HighlightOutlined,
  AlignCenterOutlined,
  AlignLeftOutlined,
  AlignRightOutlined,
  BgColorsOutlined,
  BoldOutlined,
  ItalicOutlined,
  UnderlineOutlined,
  StrikethroughOutlined,
  RedoOutlined,
  UndoOutlined,
  ZoomInOutlined,
  ZoomOutOutlined,
  FontColorsOutlined,
  FontSizeOutlined,
  LineHeightOutlined,
  DashOutlined,
  SmallDashOutlined,
  SortAscendingOutlined,
  SortDescendingOutlined,
  DragOutlined,
  OrderedListOutlined,
  UnorderedListOutlined,
  RadiusSettingOutlined,
  ColumnWidthOutlined,
  ColumnHeightOutlined,
  AreaChartOutlined,
  PieChartOutlined,
  BarChartOutlined,
  DotChartOutlined,
  LineChartOutlined,
  RadarChartOutlined,
  HeatMapOutlined,
  FallOutlined,
  RiseOutlined,
  StockOutlined,
  BoxPlotOutlined,
  FundOutlined,
  SlidersOutlined,
  AndroidOutlined,
  AppleOutlined,
  WindowsOutlined,
  IeOutlined,
  ChromeOutlined,
  GithubOutlined,
  AliwangwangOutlined,
  DingdingOutlined,
  WeiboSquareOutlined,
  WeiboCircleOutlined,
  TaobaoCircleOutlined,
  Html5Outlined,
  WeiboOutlined,
  TwitterOutlined,
  WechatOutlined,
  YoutubeOutlined,
  AlipayCircleOutlined,
  TaobaoOutlined,
  SkypeOutlined,
  QqOutlined,
  MediumWorkmarkOutlined,
  GitlabOutlined,
  MediumOutlined,
  LinkedinOutlined,
  GooglePlusOutlined,
  DropboxOutlined,
  FacebookOutlined,
  CodepenOutlined,
  CodeSandboxOutlined,
  AmazonOutlined,
  GoogleOutlined,
  CodepenCircleOutlined,
  AlipayOutlined,
  AntDesignOutlined,
  AntCloudOutlined,
  AliyunOutlined,
  ZhihuOutlined,
  SlackOutlined,
  SlackSquareOutlined,
  BehanceOutlined,
  BehanceSquareOutlined,
  DribbbleOutlined,
  DribbbleSquareOutlined,
  InstagramOutlined,
  YuqueOutlined,
  AlibabaOutlined,
  YahooOutlined,
  RedditOutlined,
  SketchOutlined,
  AccountBookOutlined,
  AimOutlined,
  AlertOutlined,
  ApartmentOutlined,
  ApiOutlined,
  AppstoreAddOutlined,
  AppstoreOutlined,
  AudioOutlined,
  AudioMutedOutlined,
  AuditOutlined,
  BankOutlined,
  BarcodeOutlined,
  BarsOutlined,
  BellOutlined,
  BlockOutlined,
  BookOutlined,
  BorderOutlined,
  BorderlessTableOutlined,
  BranchesOutlined,
  BugOutlined,
  BuildOutlined,
  BulbOutlined,
  CalculatorOutlined,
  CalendarOutlined,
  CameraOutlined,
  CarOutlined,
  CarryOutOutlined,
  CiCircleOutlined,
  CiOutlined,
  ClearOutlined,
  CloudDownloadOutlined,
  CloudOutlined,
  CloudServerOutlined,
  CloudSyncOutlined,
  CloudUploadOutlined,
  ClusterOutlined,
  CodeOutlined,
  CoffeeOutlined,
  CommentOutlined,
  CompassOutlined,
  CompressOutlined,
  ConsoleSqlOutlined,
  ContactsOutlined,
  ContainerOutlined,
  ControlOutlined,
  CopyrightOutlined,
  CreditCardOutlined,
  CrownOutlined,
  CustomerServiceOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeleteColumnOutlined,
  DeleteRowOutlined,
  DeliveredProcedureOutlined,
  DeploymentUnitOutlined,
  DesktopOutlined,
  DingtalkOutlined,
  DisconnectOutlined,
  DislikeOutlined,
  DollarCircleOutlined,
  DollarOutlined,
  DownloadOutlined,
  EllipsisOutlined,
  EnvironmentOutlined,
  EuroCircleOutlined,
  EuroOutlined,
  ExceptionOutlined,
  ExpandAltOutlined,
  ExpandOutlined,
  ExperimentOutlined,
  ExportOutlined,
  EyeOutlined,
  EyeInvisibleOutlined,
  FieldBinaryOutlined,
  FieldNumberOutlined,
  FieldStringOutlined,
  FieldTimeOutlined,
  FileAddOutlined,
  FileDoneOutlined,
  FileExcelOutlined,
  FileExclamationOutlined,
  FileOutlined,
  FileGifOutlined,
  FileImageOutlined,
  FileJpgOutlined,
  FileMarkdownOutlined,
  FilePdfOutlined,
  FilePptOutlined,
  FileProtectOutlined,
  FileSearchOutlined,
  FileSyncOutlined,
  FileTextOutlined,
  FileUnknownOutlined,
  FileWordOutlined,
  FileZipOutlined,
  FilterOutlined,
  FireOutlined,
  FlagOutlined,
  FolderAddOutlined,
  FolderOutlined,
  FolderOpenOutlined,
  FolderViewOutlined,
  ForkOutlined,
  FormatPainterOutlined,
  FrownOutlined,
  FunctionOutlined,
  FundProjectionScreenOutlined,
  FundViewOutlined,
  FunnelPlotOutlined,
  GatewayOutlined,
  GifOutlined,
  GiftOutlined,
  GlobalOutlined,
  GoldOutlined,
  GroupOutlined,
  HddOutlined,
  HeartOutlined,
  HistoryOutlined,
  HolderOutlined,
  HomeOutlined,
  HourglassOutlined,
  IdcardOutlined,
  ImportOutlined,
  InboxOutlined,
  InsertRowAboveOutlined,
  InsertRowBelowOutlined,
  InsertRowLeftOutlined,
  InsertRowRightOutlined,
  InsuranceOutlined,
  InteractionOutlined,
  KeyOutlined,
  LaptopOutlined,
  LayoutOutlined,
  LikeOutlined,
  LineOutlined,
  LinkOutlined,
  Loading3QuartersOutlined,
  LoadingOutlined,
  LockOutlined,
  MacCommandOutlined,
  MailOutlined,
  ManOutlined,
  MedicineBoxOutlined,
  MehOutlined,
  MenuOutlined,
  MergeCellsOutlined,
  MessageOutlined,
  MobileOutlined,
  MoneyCollectOutlined,
  MonitorOutlined,
  MoreOutlined,
  NodeCollapseOutlined,
  NodeExpandOutlined,
  NodeIndexOutlined,
  NotificationOutlined,
  NumberOutlined,
  OneToOneOutlined,
  PaperClipOutlined,
  PartitionOutlined,
  PayCircleOutlined,
  PercentageOutlined,
  PhoneOutlined,
  PictureOutlined,
  PlaySquareOutlined,
  PoundCircleOutlined,
  PoundOutlined,
  PoweroffOutlined,
  PrinterOutlined,
  ProfileOutlined,
  ProjectOutlined,
  PropertySafetyOutlined,
  PullRequestOutlined,
  PushpinOutlined,
  QrcodeOutlined,
  ReadOutlined,
  ReconciliationOutlined,
  RedEnvelopeOutlined,
  ReloadOutlined,
  RestOutlined,
  RobotOutlined,
  RocketOutlined,
  RotateLeftOutlined,
  RotateRightOutlined,
  SafetyCertificateOutlined,
  SafetyOutlined,
  SaveOutlined,
  ScanOutlined,
  ScheduleOutlined,
  SearchOutlined,
  SecurityScanOutlined,
  SelectOutlined,
  SendOutlined,
  SettingOutlined,
  ShakeOutlined,
  ShareAltOutlined,
  ShopOutlined,
  ShoppingCartOutlined,
  ShoppingOutlined,
  SisternodeOutlined,
  SkinOutlined,
  SmileOutlined,
  SolutionOutlined,
  SoundOutlined,
  SplitCellsOutlined,
  StarOutlined,
  SubnodeOutlined,
  SwitcherOutlined,
  SyncOutlined,
  TableOutlined,
  TabletOutlined,
  TagOutlined,
  TagsOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ToTopOutlined,
  ToolOutlined,
  TrademarkCircleOutlined,
  TrademarkOutlined,
  TransactionOutlined,
  TranslationOutlined,
  TrophyOutlined,
  UngroupOutlined,
  UnlockOutlined,
  UploadOutlined,
  UsbOutlined,
  UserAddOutlined,
  UserDeleteOutlined,
  UserOutlined,
  UserSwitchOutlined,
  UsergroupAddOutlined,
  UsergroupDeleteOutlined,
  VerifiedOutlined,
  VideoCameraAddOutlined,
  VideoCameraOutlined,
  WalletOutlined,
  WhatsAppOutlined,
  WifiOutlined,
  WomanOutlined
} from '@ant-design/icons';

export default [
  { name: 'StepBackwardOutlined', value: StepBackwardOutlined },
  { name: 'StepForwardOutlined', value: StepForwardOutlined },
  { name: 'FastBackwardOutlined', value: FastBackwardOutlined },
  { name: 'FastForwardOutlined', value: FastForwardOutlined },
  { name: 'ShrinkOutlined', value: ShrinkOutlined },
  { name: 'ArrowsAltOutlined', value: ArrowsAltOutlined },
  { name: 'DownOutlined', value: DownOutlined },
  { name: 'UpOutlined', value: UpOutlined },
  { name: 'LeftOutlined', value: LeftOutlined },
  { name: 'RightOutlined', value: RightOutlined },
  { name: 'CaretUpOutlined', value: CaretUpOutlined },
  { name: 'CaretDownOutlined', value: CaretDownOutlined },
  { name: 'CaretLeftOutlined', value: CaretLeftOutlined },
  { name: 'CaretRightOutlined', value: CaretRightOutlined },
  { name: 'UpCircleOutlined', value: UpCircleOutlined },
  { name: 'DownCircleOutlined', value: DownCircleOutlined },
  { name: 'LeftCircleOutlined', value: LeftCircleOutlined },
  { name: 'RightCircleOutlined', value: RightCircleOutlined },
  { name: 'DoubleRightOutlined', value: DoubleRightOutlined },
  { name: 'DoubleLeftOutlined', value: DoubleLeftOutlined },
  { name: 'VerticalLeftOutlined', value: VerticalLeftOutlined },
  { name: 'VerticalRightOutlined', value: VerticalRightOutlined },
  { name: 'VerticalAlignTopOutlined', value: VerticalAlignTopOutlined },
  { name: 'VerticalAlignMiddleOutlined', value: VerticalAlignMiddleOutlined },
  { name: 'VerticalAlignBottomOutlined', value: VerticalAlignBottomOutlined },
  { name: 'ForwardOutlined', value: ForwardOutlined },
  { name: 'BackwardOutlined', value: BackwardOutlined },
  { name: 'RollbackOutlined', value: RollbackOutlined },
  { name: 'EnterOutlined', value: EnterOutlined },
  { name: 'RetweetOutlined', value: RetweetOutlined },
  { name: 'SwapOutlined', value: SwapOutlined },
  { name: 'SwapLeftOutlined', value: SwapLeftOutlined },
  { name: 'SwapRightOutlined', value: SwapRightOutlined },
  { name: 'ArrowUpOutlined', value: ArrowUpOutlined },
  { name: 'ArrowDownOutlined', value: ArrowDownOutlined },
  { name: 'ArrowLeftOutlined', value: ArrowLeftOutlined },
  { name: 'ArrowRightOutlined', value: ArrowRightOutlined },
  { name: 'PlayCircleOutlined', value: PlayCircleOutlined },
  { name: 'UpSquareOutlined', value: UpSquareOutlined },
  { name: 'DownSquareOutlined', value: DownSquareOutlined },
  { name: 'LeftSquareOutlined', value: LeftSquareOutlined },
  { name: 'RightSquareOutlined', value: RightSquareOutlined },
  { name: 'LoginOutlined', value: LoginOutlined },
  { name: 'LogoutOutlined', value: LogoutOutlined },
  { name: 'MenuFoldOutlined', value: MenuFoldOutlined },
  { name: 'MenuUnfoldOutlined', value: MenuUnfoldOutlined },
  { name: 'BorderBottomOutlined', value: BorderBottomOutlined },
  { name: 'BorderHorizontalOutlined', value: BorderHorizontalOutlined },
  { name: 'BorderInnerOutlined', value: BorderInnerOutlined },
  { name: 'BorderOuterOutlined', value: BorderOuterOutlined },
  { name: 'BorderLeftOutlined', value: BorderLeftOutlined },
  { name: 'BorderRightOutlined', value: BorderRightOutlined },
  { name: 'BorderTopOutlined', value: BorderTopOutlined },
  { name: 'BorderVerticleOutlined', value: BorderVerticleOutlined },
  { name: 'PicCenterOutlined', value: PicCenterOutlined },
  { name: 'PicLeftOutlined', value: PicLeftOutlined },
  { name: 'PicRightOutlined', value: PicRightOutlined },
  { name: 'RadiusBottomleftOutlined', value: RadiusBottomleftOutlined },
  { name: 'RadiusBottomrightOutlined', value: RadiusBottomrightOutlined },
  { name: 'RadiusUpleftOutlined', value: RadiusUpleftOutlined },
  { name: 'RadiusUprightOutlined', value: RadiusUprightOutlined },
  { name: 'FullscreenOutlined', value: FullscreenOutlined },
  { name: 'FullscreenExitOutlined', value: FullscreenExitOutlined },
  { name: 'QuestionOutlined', value: QuestionOutlined },
  { name: 'QuestionCircleOutlined', value: QuestionCircleOutlined },
  { name: 'PlusOutlined', value: PlusOutlined },
  { name: 'PlusCircleOutlined', value: PlusCircleOutlined },
  { name: 'PauseOutlined', value: PauseOutlined },
  { name: 'PauseCircleOutlined', value: PauseCircleOutlined },
  { name: 'MinusOutlined', value: MinusOutlined },
  { name: 'MinusCircleOutlined', value: MinusCircleOutlined },
  { name: 'PlusSquareOutlined', value: PlusSquareOutlined },
  { name: 'MinusSquareOutlined', value: MinusSquareOutlined },
  { name: 'InfoOutlined', value: InfoOutlined },
  { name: 'InfoCircleOutlined', value: InfoCircleOutlined },
  { name: 'ExclamationOutlined', value: ExclamationOutlined },
  { name: 'ExclamationCircleOutlined', value: ExclamationCircleOutlined },
  { name: 'CloseOutlined', value: CloseOutlined },
  { name: 'CloseCircleOutlined', value: CloseCircleOutlined },
  { name: 'CloseSquareOutlined', value: CloseSquareOutlined },
  { name: 'CheckOutlined', value: CheckOutlined },
  { name: 'CheckCircleOutlined', value: CheckCircleOutlined },
  { name: 'CheckSquareOutlined', value: CheckSquareOutlined },
  { name: 'ClockCircleOutlined', value: ClockCircleOutlined },
  { name: 'WarningOutlined', value: WarningOutlined },
  { name: 'IssuesCloseOutlined', value: IssuesCloseOutlined },
  { name: 'StopOutlined', value: StopOutlined },
  { name: 'EditOutlined', value: EditOutlined },
  { name: 'FormOutlined', value: FormOutlined },
  { name: 'CopyOutlined', value: CopyOutlined },
  { name: 'ScissorOutlined', value: ScissorOutlined },
  { name: 'DeleteOutlined', value: DeleteOutlined },
  { name: 'SnippetsOutlined', value: SnippetsOutlined },
  { name: 'DiffOutlined', value: DiffOutlined },
  { name: 'HighlightOutlined', value: HighlightOutlined },
  { name: 'AlignCenterOutlined', value: AlignCenterOutlined },
  { name: 'AlignLeftOutlined', value: AlignLeftOutlined },
  { name: 'AlignRightOutlined', value: AlignRightOutlined },
  { name: 'BgColorsOutlined', value: BgColorsOutlined },
  { name: 'BoldOutlined', value: BoldOutlined },
  { name: 'ItalicOutlined', value: ItalicOutlined },
  { name: 'UnderlineOutlined', value: UnderlineOutlined },
  { name: 'StrikethroughOutlined', value: StrikethroughOutlined },
  { name: 'RedoOutlined', value: RedoOutlined },
  { name: 'UndoOutlined', value: UndoOutlined },
  { name: 'ZoomInOutlined', value: ZoomInOutlined },
  { name: 'ZoomOutOutlined', value: ZoomOutOutlined },
  { name: 'FontColorsOutlined', value: FontColorsOutlined },
  { name: 'FontSizeOutlined', value: FontSizeOutlined },
  { name: 'LineHeightOutlined', value: LineHeightOutlined },
  { name: 'DashOutlined', value: DashOutlined },
  { name: 'SmallDashOutlined', value: SmallDashOutlined },
  { name: 'SortAscendingOutlined', value: SortAscendingOutlined },
  { name: 'SortDescendingOutlined', value: SortDescendingOutlined },
  { name: 'DragOutlined', value: DragOutlined },
  { name: 'OrderedListOutlined', value: OrderedListOutlined },
  { name: 'UnorderedListOutlined', value: UnorderedListOutlined },
  { name: 'RadiusSettingOutlined', value: RadiusSettingOutlined },
  { name: 'ColumnWidthOutlined', value: ColumnWidthOutlined },
  { name: 'ColumnHeightOutlined', value: ColumnHeightOutlined },
  { name: 'AreaChartOutlined', value: AreaChartOutlined },
  { name: 'PieChartOutlined', value: PieChartOutlined },
  { name: 'BarChartOutlined', value: BarChartOutlined },
  { name: 'DotChartOutlined', value: DotChartOutlined },
  { name: 'LineChartOutlined', value: LineChartOutlined },
  { name: 'RadarChartOutlined', value: RadarChartOutlined },
  { name: 'HeatMapOutlined', value: HeatMapOutlined },
  { name: 'FallOutlined', value: FallOutlined },
  { name: 'RiseOutlined', value: RiseOutlined },
  { name: 'StockOutlined', value: StockOutlined },
  { name: 'BoxPlotOutlined', value: BoxPlotOutlined },
  { name: 'FundOutlined', value: FundOutlined },
  { name: 'SlidersOutlined', value: SlidersOutlined },
  { name: 'AndroidOutlined', value: AndroidOutlined },
  { name: 'AppleOutlined', value: AppleOutlined },
  { name: 'WindowsOutlined', value: WindowsOutlined },
  { name: 'IeOutlined', value: IeOutlined },
  { name: 'ChromeOutlined', value: ChromeOutlined },
  { name: 'GithubOutlined', value: GithubOutlined },
  { name: 'AliwangwangOutlined', value: AliwangwangOutlined },
  { name: 'DingdingOutlined', value: DingdingOutlined },
  { name: 'WeiboSquareOutlined', value: WeiboSquareOutlined },
  { name: 'WeiboCircleOutlined', value: WeiboCircleOutlined },
  { name: 'TaobaoCircleOutlined', value: TaobaoCircleOutlined },
  { name: 'Html5Outlined', value: Html5Outlined },
  { name: 'WeiboOutlined', value: WeiboOutlined },
  { name: 'TwitterOutlined', value: TwitterOutlined },
  { name: 'WechatOutlined', value: WechatOutlined },
  { name: 'YoutubeOutlined', value: YoutubeOutlined },
  { name: 'AlipayCircleOutlined', value: AlipayCircleOutlined },
  { name: 'TaobaoOutlined', value: TaobaoOutlined },
  { name: 'SkypeOutlined', value: SkypeOutlined },
  { name: 'QqOutlined', value: QqOutlined },
  { name: 'MediumWorkmarkOutlined', value: MediumWorkmarkOutlined },
  { name: 'GitlabOutlined', value: GitlabOutlined },
  { name: 'MediumOutlined', value: MediumOutlined },
  { name: 'LinkedinOutlined', value: LinkedinOutlined },
  { name: 'GooglePlusOutlined', value: GooglePlusOutlined },
  { name: 'DropboxOutlined', value: DropboxOutlined },
  { name: 'FacebookOutlined', value: FacebookOutlined },
  { name: 'CodepenOutlined', value: CodepenOutlined },
  { name: 'CodeSandboxOutlined', value: CodeSandboxOutlined },
  { name: 'AmazonOutlined', value: AmazonOutlined },
  { name: 'GoogleOutlined', value: GoogleOutlined },
  { name: 'CodepenCircleOutlined', value: CodepenCircleOutlined },
  { name: 'AlipayOutlined', value: AlipayOutlined },
  { name: 'AntDesignOutlined', value: AntDesignOutlined },
  { name: 'AntCloudOutlined', value: AntCloudOutlined },
  { name: 'AliyunOutlined', value: AliyunOutlined },
  { name: 'ZhihuOutlined', value: ZhihuOutlined },
  { name: 'SlackOutlined', value: SlackOutlined },
  { name: 'SlackSquareOutlined', value: SlackSquareOutlined },
  { name: 'BehanceOutlined', value: BehanceOutlined },
  { name: 'BehanceSquareOutlined', value: BehanceSquareOutlined },
  { name: 'DribbbleOutlined', value: DribbbleOutlined },
  { name: 'DribbbleSquareOutlined', value: DribbbleSquareOutlined },
  { name: 'InstagramOutlined', value: InstagramOutlined },
  { name: 'YuqueOutlined', value: YuqueOutlined },
  { name: 'AlibabaOutlined', value: AlibabaOutlined },
  { name: 'YahooOutlined', value: YahooOutlined },
  { name: 'RedditOutlined', value: RedditOutlined },
  { name: 'SketchOutlined', value: SketchOutlined },
  { name: 'AccountBookOutlined', value: AccountBookOutlined },
  { name: 'AimOutlined', value: AimOutlined },
  { name: 'AlertOutlined', value: AlertOutlined },
  { name: 'ApartmentOutlined', value: ApartmentOutlined },
  { name: 'ApiOutlined', value: ApiOutlined },
  { name: 'AppstoreAddOutlined', value: AppstoreAddOutlined },
  { name: 'AppstoreOutlined', value: AppstoreOutlined },
  { name: 'AudioOutlined', value: AudioOutlined },
  { name: 'AudioMutedOutlined', value: AudioMutedOutlined },
  { name: 'AuditOutlined', value: AuditOutlined },
  { name: 'BankOutlined', value: BankOutlined },
  { name: 'BarcodeOutlined', value: BarcodeOutlined },
  { name: 'BarsOutlined', value: BarsOutlined },
  { name: 'BellOutlined', value: BellOutlined },
  { name: 'BlockOutlined', value: BlockOutlined },
  { name: 'BookOutlined', value: BookOutlined },
  { name: 'BorderOutlined', value: BorderOutlined },
  { name: 'BorderlessTableOutlined', value: BorderlessTableOutlined },
  { name: 'BranchesOutlined', value: BranchesOutlined },
  { name: 'BugOutlined', value: BugOutlined },
  { name: 'BuildOutlined', value: BuildOutlined },
  { name: 'BulbOutlined', value: BulbOutlined },
  { name: 'CalculatorOutlined', value: CalculatorOutlined },
  { name: 'CalendarOutlined', value: CalendarOutlined },
  { name: 'CameraOutlined', value: CameraOutlined },
  { name: 'CarOutlined', value: CarOutlined },
  { name: 'CarryOutOutlined', value: CarryOutOutlined },
  { name: 'CiCircleOutlined', value: CiCircleOutlined },
  { name: 'CiOutlined', value: CiOutlined },
  { name: 'ClearOutlined', value: ClearOutlined },
  { name: 'CloudDownloadOutlined', value: CloudDownloadOutlined },
  { name: 'CloudOutlined', value: CloudOutlined },
  { name: 'CloudServerOutlined', value: CloudServerOutlined },
  { name: 'CloudSyncOutlined', value: CloudSyncOutlined },
  { name: 'CloudUploadOutlined', value: CloudUploadOutlined },
  { name: 'ClusterOutlined', value: ClusterOutlined },
  { name: 'CodeOutlined', value: CodeOutlined },
  { name: 'CoffeeOutlined', value: CoffeeOutlined },
  { name: 'CommentOutlined', value: CommentOutlined },
  { name: 'CompassOutlined', value: CompassOutlined },
  { name: 'CompressOutlined', value: CompressOutlined },
  { name: 'ConsoleSqlOutlined', value: ConsoleSqlOutlined },
  { name: 'ContactsOutlined', value: ContactsOutlined },
  { name: 'ContainerOutlined', value: ContainerOutlined },
  { name: 'ControlOutlined', value: ControlOutlined },
  { name: 'CopyrightOutlined', value: CopyrightOutlined },
  { name: 'CreditCardOutlined', value: CreditCardOutlined },
  { name: 'CrownOutlined', value: CrownOutlined },
  { name: 'CustomerServiceOutlined', value: CustomerServiceOutlined },
  { name: 'DashboardOutlined', value: DashboardOutlined },
  { name: 'DatabaseOutlined', value: DatabaseOutlined },
  { name: 'DeleteColumnOutlined', value: DeleteColumnOutlined },
  { name: 'DeleteRowOutlined', value: DeleteRowOutlined },
  { name: 'DeliveredProcedureOutlined', value: DeliveredProcedureOutlined },
  { name: 'DeploymentUnitOutlined', value: DeploymentUnitOutlined },
  { name: 'DesktopOutlined', value: DesktopOutlined },
  { name: 'DingtalkOutlined', value: DingtalkOutlined },
  { name: 'DisconnectOutlined', value: DisconnectOutlined },
  { name: 'DislikeOutlined', value: DislikeOutlined },
  { name: 'DollarCircleOutlined', value: DollarCircleOutlined },
  { name: 'DollarOutlined', value: DollarOutlined },
  { name: 'DownloadOutlined', value: DownloadOutlined },
  { name: 'EllipsisOutlined', value: EllipsisOutlined },
  { name: 'EnvironmentOutlined', value: EnvironmentOutlined },
  { name: 'EuroCircleOutlined', value: EuroCircleOutlined },
  { name: 'EuroOutlined', value: EuroOutlined },
  { name: 'ExceptionOutlined', value: ExceptionOutlined },
  { name: 'ExpandAltOutlined', value: ExpandAltOutlined },
  { name: 'ExpandOutlined', value: ExpandOutlined },
  { name: 'ExperimentOutlined', value: ExperimentOutlined },
  { name: 'ExportOutlined', value: ExportOutlined },
  { name: 'EyeOutlined', value: EyeOutlined },
  { name: 'EyeInvisibleOutlined', value: EyeInvisibleOutlined },
  { name: 'FieldBinaryOutlined', value: FieldBinaryOutlined },
  { name: 'FieldNumberOutlined', value: FieldNumberOutlined },
  { name: 'FieldStringOutlined', value: FieldStringOutlined },
  { name: 'FieldTimeOutlined', value: FieldTimeOutlined },
  { name: 'FileAddOutlined', value: FileAddOutlined },
  { name: 'FileDoneOutlined', value: FileDoneOutlined },
  { name: 'FileExcelOutlined', value: FileExcelOutlined },
  { name: 'FileExclamationOutlined', value: FileExclamationOutlined },
  { name: 'FileOutlined', value: FileOutlined },
  { name: 'FileGifOutlined', value: FileGifOutlined },
  { name: 'FileImageOutlined', value: FileImageOutlined },
  { name: 'FileJpgOutlined', value: FileJpgOutlined },
  { name: 'FileMarkdownOutlined', value: FileMarkdownOutlined },
  { name: 'FilePdfOutlined', value: FilePdfOutlined },
  { name: 'FilePptOutlined', value: FilePptOutlined },
  { name: 'FileProtectOutlined', value: FileProtectOutlined },
  { name: 'FileSearchOutlined', value: FileSearchOutlined },
  { name: 'FileSyncOutlined', value: FileSyncOutlined },
  { name: 'FileTextOutlined', value: FileTextOutlined },
  { name: 'FileUnknownOutlined', value: FileUnknownOutlined },
  { name: 'FileWordOutlined', value: FileWordOutlined },
  { name: 'FileZipOutlined', value: FileZipOutlined },
  { name: 'FilterOutlined', value: FilterOutlined },
  { name: 'FireOutlined', value: FireOutlined },
  { name: 'FlagOutlined', value: FlagOutlined },
  { name: 'FolderAddOutlined', value: FolderAddOutlined },
  { name: 'FolderOutlined', value: FolderOutlined },
  { name: 'FolderOpenOutlined', value: FolderOpenOutlined },
  { name: 'FolderViewOutlined', value: FolderViewOutlined },
  { name: 'ForkOutlined', value: ForkOutlined },
  { name: 'FormatPainterOutlined', value: FormatPainterOutlined },
  { name: 'FrownOutlined', value: FrownOutlined },
  { name: 'FunctionOutlined', value: FunctionOutlined },
  { name: 'FundProjectionScreenOutlined', value: FundProjectionScreenOutlined },
  { name: 'FundViewOutlined', value: FundViewOutlined },
  { name: 'FunnelPlotOutlined', value: FunnelPlotOutlined },
  { name: 'GatewayOutlined', value: GatewayOutlined },
  { name: 'GifOutlined', value: GifOutlined },
  { name: 'GiftOutlined', value: GiftOutlined },
  { name: 'GlobalOutlined', value: GlobalOutlined },
  { name: 'GoldOutlined', value: GoldOutlined },
  { name: 'GroupOutlined', value: GroupOutlined },
  { name: 'HddOutlined', value: HddOutlined },
  { name: 'HeartOutlined', value: HeartOutlined },
  { name: 'HistoryOutlined', value: HistoryOutlined },
  { name: 'HolderOutlined', value: HolderOutlined },
  { name: 'HomeOutlined', value: HomeOutlined },
  { name: 'HourglassOutlined', value: HourglassOutlined },
  { name: 'IdcardOutlined', value: IdcardOutlined },
  { name: 'ImportOutlined', value: ImportOutlined },
  { name: 'InboxOutlined', value: InboxOutlined },
  { name: 'InsertRowAboveOutlined', value: InsertRowAboveOutlined },
  { name: 'InsertRowBelowOutlined', value: InsertRowBelowOutlined },
  { name: 'InsertRowLeftOutlined', value: InsertRowLeftOutlined },
  { name: 'InsertRowRightOutlined', value: InsertRowRightOutlined },
  { name: 'InsuranceOutlined', value: InsuranceOutlined },
  { name: 'InteractionOutlined', value: InteractionOutlined },
  { name: 'KeyOutlined', value: KeyOutlined },
  { name: 'LaptopOutlined', value: LaptopOutlined },
  { name: 'LayoutOutlined', value: LayoutOutlined },
  { name: 'LikeOutlined', value: LikeOutlined },
  { name: 'LineOutlined', value: LineOutlined },
  { name: 'LinkOutlined', value: LinkOutlined },
  { name: 'Loading3QuartersOutlined', value: Loading3QuartersOutlined },
  { name: 'LoadingOutlined', value: LoadingOutlined },
  { name: 'LockOutlined', value: LockOutlined },
  { name: 'MacCommandOutlined', value: MacCommandOutlined },
  { name: 'MailOutlined', value: MailOutlined },
  { name: 'ManOutlined', value: ManOutlined },
  { name: 'MedicineBoxOutlined', value: MedicineBoxOutlined },
  { name: 'MehOutlined', value: MehOutlined },
  { name: 'MenuOutlined', value: MenuOutlined },
  { name: 'MergeCellsOutlined', value: MergeCellsOutlined },
  { name: 'MessageOutlined', value: MessageOutlined },
  { name: 'MobileOutlined', value: MobileOutlined },
  { name: 'MoneyCollectOutlined', value: MoneyCollectOutlined },
  { name: 'MonitorOutlined', value: MonitorOutlined },
  { name: 'MoreOutlined', value: MoreOutlined },
  { name: 'NodeCollapseOutlined', value: NodeCollapseOutlined },
  { name: 'NodeExpandOutlined', value: NodeExpandOutlined },
  { name: 'NodeIndexOutlined', value: NodeIndexOutlined },
  { name: 'NotificationOutlined', value: NotificationOutlined },
  { name: 'NumberOutlined', value: NumberOutlined },
  { name: 'OneToOneOutlined', value: OneToOneOutlined },
  { name: 'PaperClipOutlined', value: PaperClipOutlined },
  { name: 'PartitionOutlined', value: PartitionOutlined },
  { name: 'PayCircleOutlined', value: PayCircleOutlined },
  { name: 'PercentageOutlined', value: PercentageOutlined },
  { name: 'PhoneOutlined', value: PhoneOutlined },
  { name: 'PictureOutlined', value: PictureOutlined },
  { name: 'PlaySquareOutlined', value: PlaySquareOutlined },
  { name: 'PoundCircleOutlined', value: PoundCircleOutlined },
  { name: 'PoundOutlined', value: PoundOutlined },
  { name: 'PoweroffOutlined', value: PoweroffOutlined },
  { name: 'PrinterOutlined', value: PrinterOutlined },
  { name: 'ProfileOutlined', value: ProfileOutlined },
  { name: 'ProjectOutlined', value: ProjectOutlined },
  { name: 'PropertySafetyOutlined', value: PropertySafetyOutlined },
  { name: 'PullRequestOutlined', value: PullRequestOutlined },
  { name: 'PushpinOutlined', value: PushpinOutlined },
  { name: 'QrcodeOutlined', value: QrcodeOutlined },
  { name: 'ReadOutlined', value: ReadOutlined },
  { name: 'ReconciliationOutlined', value: ReconciliationOutlined },
  { name: 'RedEnvelopeOutlined', value: RedEnvelopeOutlined },
  { name: 'ReloadOutlined', value: ReloadOutlined },
  { name: 'RestOutlined', value: RestOutlined },
  { name: 'RobotOutlined', value: RobotOutlined },
  { name: 'RocketOutlined', value: RocketOutlined },
  { name: 'RotateLeftOutlined', value: RotateLeftOutlined },
  { name: 'RotateRightOutlined', value: RotateRightOutlined },
  { name: 'SafetyCertificateOutlined', value: SafetyCertificateOutlined },
  { name: 'SafetyOutlined', value: SafetyOutlined },
  { name: 'SaveOutlined', value: SaveOutlined },
  { name: 'ScanOutlined', value: ScanOutlined },
  { name: 'ScheduleOutlined', value: ScheduleOutlined },
  { name: 'SearchOutlined', value: SearchOutlined },
  { name: 'SecurityScanOutlined', value: SecurityScanOutlined },
  { name: 'SelectOutlined', value: SelectOutlined },
  { name: 'SendOutlined', value: SendOutlined },
  { name: 'SettingOutlined', value: SettingOutlined },
  { name: 'ShakeOutlined', value: ShakeOutlined },
  { name: 'ShareAltOutlined', value: ShareAltOutlined },
  { name: 'ShopOutlined', value: ShopOutlined },
  { name: 'ShoppingCartOutlined', value: ShoppingCartOutlined },
  { name: 'ShoppingOutlined', value: ShoppingOutlined },
  { name: 'SisternodeOutlined', value: SisternodeOutlined },
  { name: 'SkinOutlined', value: SkinOutlined },
  { name: 'SmileOutlined', value: SmileOutlined },
  { name: 'SolutionOutlined', value: SolutionOutlined },
  { name: 'SoundOutlined', value: SoundOutlined },
  { name: 'SplitCellsOutlined', value: SplitCellsOutlined },
  { name: 'StarOutlined', value: StarOutlined },
  { name: 'SubnodeOutlined', value: SubnodeOutlined },
  { name: 'SwitcherOutlined', value: SwitcherOutlined },
  { name: 'SyncOutlined', value: SyncOutlined },
  { name: 'TableOutlined', value: TableOutlined },
  { name: 'TabletOutlined', value: TabletOutlined },
  { name: 'TagOutlined', value: TagOutlined },
  { name: 'TagsOutlined', value: TagsOutlined },
  { name: 'TeamOutlined', value: TeamOutlined },
  { name: 'ThunderboltOutlined', value: ThunderboltOutlined },
  { name: 'ToTopOutlined', value: ToTopOutlined },
  { name: 'ToolOutlined', value: ToolOutlined },
  { name: 'TrademarkCircleOutlined', value: TrademarkCircleOutlined },
  { name: 'TrademarkOutlined', value: TrademarkOutlined },
  { name: 'TransactionOutlined', value: TransactionOutlined },
  { name: 'TranslationOutlined', value: TranslationOutlined },
  { name: 'TrophyOutlined', value: TrophyOutlined },
  { name: 'UngroupOutlined', value: UngroupOutlined },
  { name: 'UnlockOutlined', value: UnlockOutlined },
  { name: 'UploadOutlined', value: UploadOutlined },
  { name: 'UsbOutlined', value: UsbOutlined },
  { name: 'UserAddOutlined', value: UserAddOutlined },
  { name: 'UserDeleteOutlined', value: UserDeleteOutlined },
  { name: 'UserOutlined', value: UserOutlined },
  { name: 'UserSwitchOutlined', value: UserSwitchOutlined },
  { name: 'UsergroupAddOutlined', value: UsergroupAddOutlined },
  { name: 'UsergroupDeleteOutlined', value: UsergroupDeleteOutlined },
  { name: 'VerifiedOutlined', value: VerifiedOutlined },
  { name: 'VideoCameraAddOutlined', value: VideoCameraAddOutlined },
  { name: 'VideoCameraOutlined', value: VideoCameraOutlined },
  { name: 'WalletOutlined', value: WalletOutlined },
  { name: 'WhatsAppOutlined', value: WhatsAppOutlined },
  { name: 'WifiOutlined', value: WifiOutlined },
  { name: 'WomanOutlined', value: WomanOutlined }
];
